# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edc52df9af94f3675a853d307d49d0bc983a43224cd22946122c65194d4012b1a84af37283e1ee19e94302f143497804df1a1acab5de85b34523439674ce390e

test:
  secret_key_base: cb797c96c3989799913fdf0918e230001295b65dfaf848dfca411f1a4e8be243aef1732e4bdc48f3f7d3ecbed3319104f3c1b4aac458e0568f36aa4db92cca8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
